### ISSUE TITLE
Wrong version number in setup.py?

### ISSUE THREAD

**Issue by gudlot** [maxiv-science/azint#4]
I am confused because I installed azint according to the manual. Pip list shows me version 0.8.4 and conda list shows 0.8.5.
I looked at https://github.com/maxiv-science/azint/blob/master/setup.py on the master branch. 
There is version 0.8.4 given, but the master branch tag is 0.8.5. Is this why I see different versions? 

Related to this question, how can I check for azint the version number in Jupyter, please? To the best of my knowledge there is no `azint.__version__`

Thank you.

**Comment by weninc** [comment]
thanks that is fixed with the move to setuptools_scm and there is now also azint.__version__
